<a href="https://colab.research.google.com/github/HannanSheikh/python_Numpy/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [ ]:
np.random.rand(5)

array([0.90532263, 0.34182877, 0.83338497, 0.78727946, 0.82134073])

In [ ]:
my_array=np.random.randint(1,5,10)

In [ ]:
my_array

array([2, 3, 3, 4, 4, 4, 2, 3, 3, 2])

In [ ]:
my_array.min()

1

In [ ]:
my_array.max()

4

In [ ]:
my_array.argmin() # min ka index

8

In [ ]:
my_array.argmax() # max ka index

2

In [ ]:
arr1 = my_array.copy()

In [ ]:
arr1

array([2, 3, 4, 4, 4, 3, 2, 4, 1, 3])

In [ ]:
arr1[0]=4
arr1

array([4, 3, 4, 4, 4, 3, 2, 4, 1, 3])

In [ ]:
my_array

array([2, 3, 4, 4, 4, 3, 2, 4, 1, 3])

In [ ]:
arr_2d=np.array([[1,2,3],[20,25,30],[105,110,120]])
arr_2d

array([[  1,   2,   3],
       [ 20,  25,  30],
       [105, 110, 120]])

In [ ]:
arr_2d[1,2]

30

In [ ]:
arr_2d[1:] # 1th row se onwards data

array([[ 20,  25,  30],
       [105, 110, 120]])

In [ ]:
arr_2d[1:,1:]


array([[ 25,  30],
       [110, 120]])

In [ ]:
my_array[my_array > 3]

array([4, 4, 4, 4])

In [ ]:
my_array

array([2, 3, 3, 4, 4, 4, 2, 3, 3, 2])

In [ ]:
my_array + my_array

array([4, 6, 6, 8, 8, 8, 4, 6, 6, 4])

In [ ]:
my_array - my_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
my_array * my_array

array([ 4,  9,  9, 16, 16, 16,  4,  9,  9,  4])

In [ ]:
my_array / my_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
new_array=my_array + 10

In [ ]:
new_array >12

array([False,  True,  True,  True,  True,  True, False,  True,  True,
       False])